# Introduction
In this final project of Web Analytics course, we worked on building a movie recommender system based on movie's text scraped from Wikipedia.

In [1]:
##Import all the required packages
import pandas as pd
import numpy as np
from IPython.display import display # Allows the use of display() for DataFrames
import time
import pickle #To save the objects that were created using webscraping
import pprint
from lxml import html
import requests
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
from urllib.request import urlopen
from bs4 import BeautifulSoup

import urllib
import os

import os
import re
import nltk
import string
from collections import Counter

# Data collection

We scraped the text related to movie's plot from Wikipedia using a Python based web robot. The design of this web robot is present at: 


The data collection is divided into 2 phases:

1. In the first phase the web robot has successfully scraped the list of target movie URLs, by iteratively visiting theweb site  https://en.wikipedia.org/wiki/List_of_American_films_of_xxxx (where xxxx represent the year. For example, to obtain the list of american movies released in 2000, we have to visit the website https://en.wikipedia.org/wiki/List_of_American_films_of_2000). From each URL the web robot will get the list of movie names, movie's Wiki page, cast, director and genre details. We scraped the list of movies for the years 2000-2016. A total of 4045 movies list was obtained. 

2. In the secod phase the web robot has visited all the 4045 URLs, and has successfully downloaded the movies plots from wikipedia. The web robot has run for approximately 7 hours to download 4045 movies text (we purposefully used a delay of 3 seconds between every hit, so that we do not overwhlem the wikipedia server with constant hits). 

The output of phase-1 is a comma separated file, with the following details: 

**Movie** - Movie Name

**URL** - Wikipedia web page for the movie

**Year** - Year of release

**Director** - Director of the movie

**Cast** - Cast of the movie

**Genre** - Movie's genre

**Movie_ID** - Unique key to distinguish each movie

In [2]:
URL = pd.read_csv("Movies_URL_Latest.csv")
#URL[URL["Movie_ID"] == 899]
display(URL.head())
print(URL.shape)

,Movie,URL,Year,Director,Cast,Genre,Movie_ID
0,102 Dalmatians,https://en.wikipedia.org/wiki/102_Dalmatians,2000,Kevin Lima,"Glenn Close, Gérard Depardieu, Alice Evans","Comedy, family",1
1,28 Days,https://en.wikipedia.org/wiki/28_Days_(film),2000,Betty Thomas,"Sandra Bullock, Viggo Mortensen",Drama,2
2,3 Strikes,https://en.wikipedia.org/wiki/3_Strikes_(film),2000,DJ Pooh,"Brian Hooks, N'Bushe Wright",Comedy,3
3,The 6th Day,https://en.wikipedia.org/wiki/The_6th_Day,2000,Roger Spottiswoode,"Arnold Schwarzenegger, Robert Duvall",Science fiction,4
4,Across the Line,https://en.wikipedia.org/wiki/Across_the_Line_...,2000,Martin Spottl,"Brad Johnson, Adrienne Barbeau, Brian Bloom",Thriller,5

(4045, 7)

The output of phase-2 is 4045 text files and image files (Not all the movies and images were downloaded. But will be fixed later). The output of phase-2 (text files) is further processed (cleaned by removing unnecessary characters, stop words etc) to create a CSV file, with the following format.

**Movie_ID** - Unique ID of the movie

**Plot** - Plot of the movie

The initial rows of this file is displayed below:

In [3]:
df = pd.read_csv("processed_data.csv")
df.head()

   Movie_ID                                               Plot
0         1  102 dalmatians 2000 american family comedy fil...
1        10  american psycho 2000 american black comedy hor...
2       100  legacy 2000 american documentary film directed...
3      1000  lemony snicket series unfortunate events 2004 ...
4      1001  life death peter sellers 2004 british-american...

# Building the recommender

## Get the TFIDF scores

Using the data frame, we have to get the TFIDF scores for all the words in each of the document.

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df["Plot"])
print(tfidf_matrix.shape)

(4037, 54075)

## Get the cosine similarity measure between each pair of movie

In [182]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)


#Convert cos_sim (a numpy array) to a data frame with rows and columns as movie IDs
cos_sim_df = pd.DataFrame(cos_sim,columns=df["Movie_ID"].tolist(),index=df["Movie_ID"].tolist())

In [184]:
#Get the mapping between available Movie plots and movie IDs
Movie_Map=pd.merge(URL[["Movie","Movie_ID"]],df,how='inner',on=["Movie_ID"])[["Movie","Movie_ID"]]

def Get_Recommendations(Movie_ID,cos_sim_df):
    recommended_idx=np.argpartition(np.array(cos_sim_df[Movie_ID].tolist()), -6)[-6:]
    Recommended_Movie_IDs = cos_sim_df.columns[recommended_idx].tolist()
    return Recommended_Movie_IDs

# Get recommendations for the Movie_IDs: [1, 73, 3316, 3883]
Recommended_Movies = Get_Recommendations(1,cos_sim_df)
#
#recommended_idx=np.argpartition(np.array(cos_sim_df[1].tolist()), -6)[-6:]
#Recommended_Movies = cos_sim_df.columns[recommended_idx].tolist()
Movie_Map[Movie_Map["Movie_ID"].isin(Recommended_Movies)]


Recommended_Movies = Get_Recommendations(73,cos_sim_df)
Movie_Map[Movie_Map["Movie_ID"].isin(Recommended_Movies)]

Recommended_Movies = Get_Recommendations(3316,cos_sim_df)
Movie_Map[Movie_Map["Movie_ID"].isin(Recommended_Movies)]

Recommended_Movies = Get_Recommendations(3883,cos_sim_df)
Movie_Map[Movie_Map["Movie_ID"].isin(Recommended_Movies)]

                                    Movie  Movie_ID
359                           On the Line       360
427   What's the Worst That Could Happen?       428
848                          Stuck on You       851
2265                             17 Again      2269
2609                       Lottery Ticket      2614
3874                              Minions      3883

Cosine similarity is a numpy array.

In [161]:
recommended_idx=np.argpartition(cos_sim[0], -6)[-6:]
df.iloc[recommended_idx]

      Movie_ID                                               Plot
1793      2614  lottery ticket 2010 american comedy film direc...
887       1799  blue state canadian american romantic comedy f...
1201      2080  beverly hills chihuahua 2008 american family c...
2846      3564  cold comes night 2013 american crime thriller ...
3660       659  101 dalmatians ii patch london adventure 2003 ...
0            1  102 dalmatians 2000 american family comedy fil...

## Get the recommendations

Let us assume that the user likes the following movies:

In [74]:
from IPython.display import HTML, display

display(HTML("<table><tr><td><img src='./images/1.jpg'></td> \
             <td><img src='./images/73.jpg'></td> \
             <td><img src='./images/3316.jpg'></td>\
             <td><img src='./images/3883.jpg'></td></tr></table>" \
            ))

In [165]:
Movie_Map=pd.merge(URL[["Movie","Movie_ID"]],df,how='inner',on=["Movie_ID"])[["Movie","Movie_ID"]]
Movie_Map["cosine_index"] = range(cos_sim.shape[0])
#print(cos_sim.shape)
#display(Movie_Map.tail())
idx = list(Movie_Map[Movie_Map["Movie_ID"]==74]["cosine_index"])[0]
print(idx)
#print(cos_sim[idx])
recommended_idx=np.argpartition(cos_sim[idx], -6)[-6:]
df.iloc[recommended_idx]
#print(recommended_idx)
#print(Movie_Map["cosine_index"].isin(recommended_idx))
#recommended_IDs = Movie_Map[Movie_Map["cosine_index"].isin(recommended_idx)]
#recommended_IDs
#print(idx)

#cos_sim_df=pd.DataFrame(cos_sim,columns=list(Movie_Map["Movie_ID"])
#                        ,index=list(Movie_Map["Movie_ID"])
#                       )
#cos_sim_df
#ind = np.argpartition(np.array(cos_sim_df.loc[73]), -6)[-6:]
#ind = list(Movie_Map["Movie_ID"])[ind]
#print(ind)
#print(df.loc[ind])
#Movie_Map[Movie_Map["Movie_ID"]==73]
#cos_sim_df.loc["Gladiator"][72]
#np.argpartition(cos_sim[idx], -6)[-6:]

73

      Movie_ID                                               Plot
1713      2542  dinner schmucks 2010 american comedy film dire...
2038      2836  paranormal activity 2011 american found footag...
2824      3544  warm bodies 2013 american paranormal romantic ...
1654       249  business strangers 2001 film tells story event...
73        1064  sleepover 2004 american teen film directed joe...
2283      3057  friends kids 2011 american romantic comedy fil...

In [156]:
#Get the mapping between Movie name and its ID (since some of the URLs were NOT scraped successfully)
Movie_Map=pd.merge(URL[["Movie","Movie_ID"]],df,how='inner',on=["Movie_ID"])[["Movie","Movie_ID"]]

def Get_Recommendations(id,cos_sim,Movie_Map):
    idx = list(Movie_Map[(Movie_Map["Movie_ID"] == id)].index)[0]
    print(idx)
    ind = np.argpartition(cos_sim[idx], -6)[-6:]
    #ind
    print(df.iloc[ind])


#Movie_Map.head()
#print("The movie IDs of above 4 movies are: {}".format([1, 73, 3316, 3883]))
#Movie_Map
Get_Recommendations(73,cos_sim,Movie_Map)

72
      Movie_ID                                               Plot
2327      3097  looper 2012 american neo-noir science fiction ...
2651      3389  joe 2013 independent drama film directed co-pr...
3481       498  dragonfly 2002 supernatural fantasy film direc...
633        157  scarecrow 2000 animated musical fantasy film w...
3913       888  along came polly 2004 american romantic comedy...
72        1063  sky captain world tomorrow 2004 american scien...

In [73]:
#Get the IDs of the interested movies:
interested_movies = ["Gladiator","102 Dalmatians","Frozen","Minions"]
#[i for i,x in enumerate(Movie) for j in interested_movies if x.strip().lower() == j.strip().lower()]
#[1, 73, 3316, 3883]
Interested_Movie_ID=[i for i,x in zip(list(URL["Movie_ID"]), \
                                      list(URL["Movie"])) \
                                      for j in interested_movies \
                                      if x.strip().lower() == j.strip().lower()]




#array([[ 1.        ,  0.36651513,  0.52305744,  0.13448867]])
#sorted(cos_sim[0])[-5:]
ind = np.argpartition(cos_sim[0], -4)[-4:]
ind
df.iloc[ind]
#cos_sim[0][ind]

      Movie_ID                                               Plot
1201      2080  beverly hills chihuahua 2008 american family c...
2846      3564  cold comes night 2013 american crime thriller ...
3660       659  101 dalmatians ii patch london adventure 2003 ...
0            1  102 dalmatians 2000 american family comedy fil...

In [64]:
pd.merge(URL[["Movie","Movie_ID"]],df,how='inner',on=["Movie_ID"])

,Movie,Movie_ID,Plot
0,102 Dalmatians,1,102 dalmatians 2000 american family comedy fil...
1,28 Days,2,28 days 2000 american comedy-drama film direct...
2,3 Strikes,3,strikes 2000 american screwball comedy film wr...
3,The 6th Day,4,6th day 2000 american science fiction action f...
4,Across the Line,5,across line 2000 american drama film directed ...
5,Adventures in Wild California,6,adventures wild california 70mm american docum...
6,The Adventures of Rocky and Bullwinkle,7,adventures rocky bullwinkle 2000 live action/a...
7,All the Pretty Horses,8,pretty horses 2000 american romance western fi...
8,Almost Famous,9,almost famous 2000 american comedy-drama film ...
9,American Psycho,10,american psycho 2000 american black comedy hor...
10,Animal Factory,11,animal factory 2000 crime drama film life pris...
11,The Art of War,12,art war 2000 canadian-american action film dir...
12,Autumn in New York,13,autumn new york 2000 american romantic drama f...
13,Bait,14,bait 2000 canadian-american comedy crime film ...
14,Bamboozled,15,bamboozled 2000 satirical film written directe...
15,Battlefield Earth,16,battlefield earth also referred battlefield ea...
16,The Beach,17,beach 2000 british-american adventure drama fi...
17,Beat,18,beat 2000 american drama film written directed...
18,Beautiful,19,beautiful 2000 american comedy-drama film dire...
19,Beautiful Joe,20,beautiful joe 2000 american-british film writt...
20,Bedazzled,21,bedazzled 2000 black-comedy film remake 1967 f...
21,Before Night Falls,22,night falls 2000 american biographical romanti...
22,Best in Show,23,best show 2000 american mockumentary comedy fi...
23,Big Momma's House,24,big momma house 2000 american action comedy fi...
24,The Big Tease,25,big tease 1999 comedy film starring craig ferg...
25,Bless the Child,26,bless child 2000 german-american horror-thrill...
26,Boiler Room,27,boiler room 2000 american crime drama film wri...
27,Book of Shadows: Blair Witch 2,28,book shadows blair witch also known blair witc...
28,Bounce,29,bounce 2000 american romantic drama film starr...
29,A Boy Named Sue,30,boy named sue 2001 documentary film directed j...
...,...,...,...
4007,When the Bough Breaks,4016,bough breaks 2016 american psychological thril...
4008,The Wild Life,4017,robinson crusoe released north america wild li...
4009,The Disappointments Room,4018,disappointments room 2016 american psychologic...
4010,Bridget Jones's Baby,4019,bridget jones baby 2016 romantic comedy film d...
4011,Snowden,4020,snowden 2016 american-german biographical poli...
4012,Blair Witch,4021,blair witch 2016 american found footage supern...
4013,Hillsong: Let Hope Rise,4022,hillsong let hope rise 2016 american christian...
4014,The Magnificent Seven,4023,magnificent seven 2016 american western action...
4015,Storks,4024,storks 2016 american 3d computer-animated adve...
4016,South of 8,4025,south 2016 american crime film written first t...
4017,Miss Peregrine's Home for Peculiar Children,4026,miss peregrine home peculiar children 2016 ame...
4018,Deepwater Horizon,4027,deepwater horizon 2016 american biopic disaste...
4019,Masterminds,4028,masterminds 2016 american comedy film based 19...
4020,The Girl on the Train,4029,girl train 2016 american mystery thriller dram...
4021,The Birth of a Nation,4030,birth nation 2016 american period drama film b...
4022,Middle School: The Worst Years of My Life,4031,middle school worst years life 2016 american l...
4023,The Accountant,4032,accountant 2016 american crime thriller film d...
4024,Kevin Hart: What Now?,4033,kevin hart ? 2016 american stand-up comedy con...
4025,Max Steel,4034,max steel 2016 american superhero science fict...
4026,Jack Reacher: Never Go Back,4035,jack reacher never go back 2016 american actio...
4027,Keeping Up with the Joneses,4036,keeping joneses 2016 american action comedy fi...
4028,Ouija: Origin of Evil,4037,ouija origin evil 2016 american supernatural h...
4029,Boo! A Madea Halloween,4038,boo madea halloween 2016 american comedy horro...
4030,I'm Not Ashamed,4039,ashamed 2016 biographical drama film based jou...
4031,American Pastoral,4040,american pastoral 2016 american crime-drama fi...
4032,Inferno,4041,inferno 2016 american mystery thriller film di...
4033,Friend Request,4042,friend request german title unfriend 2016 germ...
4034,Rogue One: A Star Wars Story (film),4043,rogue one star wars story simply rogue one 201...
4035,The Founder,4044,founder 2016 american biographical drama film ...
4036,Rings,4045,rings 2017 american supernatural psychological...

In [49]:
interested_movies = ["Gladiator","102 Dalmatians","Frozen","Minions"]
#[i for i,x in enumerate(Movie) for j in interested_movies if x.strip().lower() == j.strip().lower()]
#[1, 73, 3316, 3883]
Interested_Movie_ID=[i for i,x in zip(list(URL["Movie_ID"]), \
                                      list(URL["Movie"])) \
                                      for j in interested_movies \
                                      if x.strip().lower() == j.strip().lower()]
#Image_Files = 
#for i Movie for j in ["Gladiator","Matrix","102 Dalmatians"]

In [42]:
from IPython.display import HTML, display

display(HTML("<table><tr><td><img src='./images/1.jpg'></td> \
             <td><img src='./images/73.jpg'></td> \
             <td><img src='./images/3316.jpg'></td>\
             <td><img src='./images/3883.jpg'></td></tr></table>" \
            ))

In [38]:
cosine_sim_df=pd.DataFrame(cos_sim)
cosine_sim_df.columns = list(df["Movie_ID"])
cosine_sim_df.index = list(df["Movie_ID"])
#cosine_sim_df.columns = list(Movie)
#cosine_sim_df.index = list(Movie)

cosine_sim_df

,1,10,100,1000,1001,1002,1003,1004,1005,1006,...,990,991,992,993,994,995,996,997,998,999
1,1.000000,0.013110,0.025153,0.016308,0.011577,0.007299,0.010271,0.010509,0.006320,0.009129,...,0.011846,0.008216,0.011399,0.005237,0.007315,0.006427,0.008360,0.006734,0.002983,0.006313
10,0.013110,1.000000,0.009444,0.012178,0.004680,0.005145,0.009484,0.008657,0.011202,0.007491,...,0.013249,0.017382,0.007149,0.007385,0.011362,0.004854,0.019540,0.013429,0.000961,0.004964
100,0.025153,0.009444,1.000000,0.016322,0.059142,0.027863,0.014048,0.036151,0.007757,0.006688,...,0.042228,0.001339,0.009732,0.007993,0.013280,0.009319,0.021211,0.006464,0.023891,0.016957
1000,0.016308,0.012178,0.016322,1.000000,0.004812,0.024725,0.011021,0.018253,0.011957,0.012848,...,0.034581,0.014664,0.008955,0.009943,0.010786,0.008122,0.021269,0.020851,0.005010,0.009184
1001,0.011577,0.004680,0.059142,0.004812,1.000000,0.006460,0.007578,0.032768,0.004027,0.009007,...,0.009151,0.002705,0.014901,0.004565,0.016529,0.044348,0.009097,0.007988,0.014264,0.025655
1002,0.007299,0.005145,0.027863,0.024725,0.006460,1.000000,0.006180,0.015325,0.006960,0.030447,...,0.015545,0.013500,0.031731,0.008173,0.010223,0.007692,0.015265,0.008178,0.010762,0.013937
1003,0.010271,0.009484,0.014048,0.011021,0.007578,0.006180,1.000000,0.009379,0.007544,0.010232,...,0.027237,0.018090,0.007262,0.006958,0.008695,0.009016,0.010088,0.012814,0.011469,0.015597
1004,0.010509,0.008657,0.036151,0.018253,0.032768,0.015325,0.009379,1.000000,0.013861,0.013198,...,0.013786,0.027088,0.012796,0.010316,0.018577,0.009816,0.023062,0.009664,0.007165,0.012340
1005,0.006320,0.011202,0.007757,0.011957,0.004027,0.006960,0.007544,0.013861,1.000000,0.018479,...,0.011095,0.013903,0.015171,0.006398,0.006556,0.006096,0.010419,0.014563,0.004381,0.005944
1006,0.009129,0.007491,0.006688,0.012848,0.009007,0.030447,0.010232,0.013198,0.018479,1.000000,...,0.006813,0.011289,0.014773,0.010392,0.007992,0.007115,0.015426,0.007499,0.003727,0.018923
1007,0.012161,0.006834,0.031098,0.019809,0.016764,0.008200,0.005869,0.028042,0.008751,0.008400,...,0.011436,0.028734,0.010079,0.010203,0.015886,0.009649,0.015464,0.016156,0.005658,0.009214
1008,0.005168,0.017228,0.004783,0.014488,0.003851,0.007814,0.025487,0.013173,0.012126,0.008498,...,0.015284,0.016052,0.006531,0.011101,0.012965,0.012294,0.010587,0.025293,0.005867,0.008411
1009,0.006860,0.006283,0.002877,0.010189,0.008098,0.005978,0.008856,0.014339,0.005008,0.005503,...,0.007776,0.011979,0.006603,0.004717,0.011319,0.003092,0.008724,0.007147,0.003291,0.007802
101,0.007217,0.006228,0.016035,0.013586,0.006717,0.004289,0.014910,0.016476,0.007636,0.007138,...,0.014681,0.011602,0.012217,0.006177,0.007519,0.005455,0.030210,0.017575,0.004849,0.006820
1010,0.012828,0.011837,0.005898,0.011563,0.002839,0.007153,0.011027,0.013573,0.008332,0.008729,...,0.009084,0.016495,0.007124,0.008898,0.013040,0.068299,0.227024,0.019285,0.003313,0.010485
1011,0.002369,0.007200,0.004407,0.014103,0.060245,0.012932,0.013007,0.011664,0.008578,0.006249,...,0.018062,0.004450,0.015288,0.003126,0.007379,0.033813,0.064706,0.008954,0.021246,0.038163
1012,0.002352,0.005225,0.004948,0.003813,0.019987,0.005936,0.005744,0.010136,0.011901,0.005184,...,0.010874,0.007182,0.019121,0.002146,0.003189,0.018820,0.006491,0.007848,0.017821,0.007116
1013,0.009021,0.008068,0.009987,0.013779,0.005803,0.008468,0.014385,0.013991,0.012237,0.006871,...,0.033674,0.019053,0.005138,0.007971,0.011728,0.005330,0.012311,0.009149,0.009674,0.011986
1014,0.006049,0.003348,0.042446,0.008618,0.028980,0.018278,0.010611,0.016392,0.016902,0.017354,...,0.036515,0.008566,0.037426,0.006288,0.008666,0.042064,0.008627,0.010843,0.074431,0.024254
1015,0.011783,0.028707,0.004563,0.024459,0.007988,0.012881,0.014013,0.018540,0.013141,0.022323,...,0.005712,0.020606,0.023503,0.012402,0.013998,0.008953,0.024374,0.024874,0.006722,0.037532
1016,0.006527,0.011595,0.007311,0.012065,0.009269,0.017188,0.013721,0.016822,0.009899,0.023049,...,0.021691,0.022327,0.018246,0.010195,0.014925,0.006491,0.044771,0.018244,0.007313,0.010776
1017,0.013588,0.004501,0.004908,0.012455,0.005210,0.014692,0.012983,0.008832,0.012551,0.005058,...,0.008093,0.017537,0.013004,0.007723,0.010609,0.009309,0.014489,0.016842,0.007471,0.006688
1018,0.004493,0.005355,0.075642,0.008378,0.028305,0.027055,0.011851,0.022230,0.008660,0.006233,...,0.044089,0.012935,0.072491,0.010983,0.004716,0.041748,0.029477,0.008897,0.042779,0.028337
1019,0.008922,0.001772,0.088560,0.008358,0.029135,0.023489,0.017657,0.021178,0.004580,0.012630,...,0.023838,0.008846,0.039326,0.005078,0.008329,0.052986,0.009593,0.008595,0.043998,0.015136
102,0.010463,0.016268,0.008494,0.012740,0.017658,0.005935,0.008634,0.013455,0.005932,0.009994,...,0.009232,0.016796,0.007441,0.010053,0.012698,0.008732,0.011629,0.012894,0.002869,0.005706
1020,0.004388,0.010141,0.007081,0.011539,0.010282,0.004343,0.007069,0.009985,0.007576,0.009854,...,0.019900,0.006346,0.008514,0.006933,0.007544,0.008791,0.020743,0.008000,0.007817,0.013425
1021,0.005920,0.019551,0.007954,0.017934,0.021514,0.009532,0.013417,0.012348,0.007245,0.010113,...,0.017899,0.012090,0.024922,0.005618,0.011920,0.017158,0.017860,0.013307,0.007110,0.011921
1022,0.008803,0.008500,0.015811,0.025692,0.010491,0.011157,0.027993,0.026839,0.012209,0.008641,...,0.035492,0.026227,0.020864,0.009336,0.016479,0.012327,0.014059,0.011805,0.008456,0.019621
1023,0.009560,0.015559,0.029976,0.014922,0.013450,0.011879,0.014758,0.034183,0.016698,0.015088,...,0.013746,0.034001,0.020833,0.014689,0.016682,0.094306,0.017457,0.017915,0.010469,0.013110
1024,0.006224,0.011056,0.013350,0.014525,0.006918,0.013057,0.007531,0.017613,0.010216,0.016489,...,0.015705,0.018229,0.023846,0.005708,0.014373,0.014641,0.011403,0.012598,0.013830,0.017007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972,0.009681,0.007004,0.004076,0.013946,0.009610,0.006150,0.016548,0.011914,0.005906,0.004668,...,0.008714,0.012380,0.019007,0.006320,0.008868,0.005235,0.009105,0.009410,0.003878,0.002750
973,0.010037,0.010688,0.030123,0.005557,0.045752,0.000975,0.001440,0.017814,0.005781,0.004993,...,0.020029,0.012042,0.028064,0.006425,0.005003,0.018431,0.008652,0.001164,0.002068,0.018205
974,0.003963,0.004449,0.005801,0.007455,0.001955,0.006100,0.006789,0.006730,0.004720,0.007324,...,0.009394,0.006527,0.006378,0.005327,0.007554,0.003799,0.010164,0.006539,0.002262,0.013221
975,0.001507,0.005981,0.005906,0.001234,0.003822,0.010084,0.003405,0.002593,0.002076,0.005428,...,0.010683,0.001684,0.017859,0.000995,0.001915,0.019017,0.007463,0.009032,0.007086,0.019333
976,0.005268,0.007586,0.005233,0.013073,0.018016,0.005943,0.009229,0.014910,0.012079,0.009841,...,0.005081,0.012100,0.019569,0.014382,0.007257,0.008127,0.012450,0.006839,0.006722,0.010612
977,0.002228,0.020208,0.003584,0.011665,0.007240,0.007243,0.009560,0.004291,0.008988,0.008407,...,0.013713,0.011757,0.038156,0.003220,0.005177,0.023172,0.010399,0.014328,0.010987,0.006924
978,0.014239,0.013449,0.055582,0.017650,0.055002,0.063739,0.010727,0.113403,0.010396,0.022355,...,0.020644,0.030905,0.018480,0.010765,0.068439,0.034871,0.022447,0.009205,0.010526,0.012282
979,0.011750,0.008395,0.009136,0.013261,0.002887,0.006216,0.010433,0.012739,0.006609,0.004368,...,0.010544,0.006378,0.006639,0.007573,0.004963,0.003374,0.039228,0.046103,0.010677,0.017898
98,0.002561,0.009913,0.004767,0.010953,0.025717,0.005133,0.017264,0.003866,0.002850,0.003310,...,0.010271,0.008750,0.014393,0.002136,0.006481,0.013842,0.006647,0.006819,0.003165,0.003714
980,0.006966,0.080107,0.021908,0.013319,0.006779,0.006613,0.004489,0.012278,0.014525,0.017829,...,0.015832,0.015677,0.007189,0.017788,0.009527,0.007595,0.010954,0.016469,0.004527,0.005296
981,0.003511,0.008100,0.025254,0.009503,0.037620,0.013184,0.012637,0.009581,0.007887,0.017866,...,0.015634,0.004471,0.070141,0.002560,0.010547,0.032202,0.007768,0.013911,0.019985,0.023368
982,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.006439,0.000000,0.002168,...,0.000000,0.000000,0.000000,0.001834,0.004297,0.000000,0.000000,0.003692,0.000000,0.000000
983,0.008722,0.015061,0.013522,0.010571,0.006744,0.006470,0.008954,0.013496,0.007023,0.008841,...,0.009325,0.005477,0.003050,0.007521,0.010046,0.005260,0.005739,0.010184,0.002609,0.006604
984,0.014441,0.014108,0.043739,0.021406,0.015499,0.010308,0.007174,0.045110,0.017182,0.010931,...,0.030611,0.029189,0.010037,0.014158,0.020462,0.012004,0.020651,0.025006,0.010707,0.015237
985,0.011299,0.013814,0.028086,0.046124,0.007003,0.010765,0.010802,0.010696,0.010400,0.009144,...,0.018938,0.012429,0.014927,0.011728,0.008712,0.005369,0.100032,0.034756,0.003715,0.007194
986,0.007509,0.018454,0.013864,0.015821,0.005327,0.008527,0.014062,0.037035,0.011097,0.007404,...,0.017779,0.026774,0.013204,0.007362,0.014242,0.012760,0.027104,0.009781,0.004729,0.008701
987,0.009902,0.014218,0.005377,0.011105,0.004166,0.006638,0.010225,0.017329,0.008726,0.009962,...,0.007410,0.022665,0.019857,0.008678,0.025791,0.017002,0.016181,0.010019,0.014006,0.008005
988,0.002860,0.011601,0.027264,0.004472,0.010228,0.009590,0.009133,0.016486,0.004346,0.004346,...,0.010503,0.008476,0.013526,0.004431,0.011355,0.013226,0.007761,0.005696,0.017549,0.013802
989,0.022378,0.011796,0.039465,0.016096,0.010164,0.012404,0.024392,0.025727,0.010568,0.012238,...,0.024324,0.037063,0.015724,0.030620,0.018306,0.010708,0.025229,0.010973,0.009599,0.013676
99,0.007429,0.005828,0.024114,0.006961,0.014845,0.014686,0.027022,0.012402,0.007944,0.010018,...,0.012748,0.007495,0.012009,0.008529,0.009341,0.004945,0.008562,0.014239,0.001918,0.032597
990,0.011846,0.013249,0.042228,0.034581,0.009151,0.015545,0.027237,0.013786,0.011095,0.006813,...,1.000000,0.011686,0.020587,0.007312,0.008677,0.022572,0.012851,0.007790,0.022799,0.019821
991,0.008216,0.017382,0.001339,0.014664,0.002705,0.013500,0.018090,0.027088,0.013903,0.011289,...,0.011686,1.000000,0.009799,0.011033,0.011231,0.010901,0.014255,0.011695,0.009130,0.006606
992,0.011399,0.007149,0.009732,0.008955,0.014901,0.031731,0.007262,0.012796,0.015171,0.014773,...,0.020587,0.009799,1.000000,0.006303,0.029171,0.049719,0.012454,0.016395,0.021066,0.012125
993,0.005237,0.007385,0.007993,0.009943,0.004565,0.008173,0.006958,0.010316,0.006398,0.010392,...,0.007312,0.011033,0.006303,1.000000,0.007187,0.003555,0.015352,0.020159,0.003244,0.004920
994,0.007315,0.011362,0.013280,0.010786,0.016529,0.010223,0.008695,0.018577,0.006556,0.007992,...,0.008677,0.011231,0.029171,0.007187,1.000000,0.005816,0.013668,0.010266,0.008074,0.005890
995,0.006427,0.004854,0.009319,0.008122,0.044348,0.007692,0.009016,0.009816,0.006096,0.007115,...,0.022572,0.010901,0.049719,0.003555,0.005816,1.000000,0.013595,0.009792,0.023676,0.012702
996,0.008360,0.019540,0.021211,0.021269,0.009097,0.015265,0.010088,0.023062,0.010419,0.015426,...,0.012851,0.014255,0.012454,0.015352,0.013668,0.013595,1.000000,0.023769,0.009953,0.010390
997,0.006734,0.013429,0.006464,0.020851,0.007988,0.008178,0.012814,0.009664,0.014563,0.007499,...,0.007790,0.011695,0.016395,0.020159,0.010266,0.009792,0.023769,1.000000,0.004300,0.014436
998,0.002983,0.000961,0.023891,0.005010,0.014264,0.010762,0.011469,0.007165,0.004381,0.003727,...,0.022799,0.009130,0.021066,0.003244,0.008074,0.023676,0.009953,0.004300,1.000000,0.012729
999,0.006313,0.004964,0.016957,0.009184,0.025655,0.013937,0.015597,0.012340,0.005944,0.018923,...,0.019821,0.006606,0.012125,0.004920,0.005890,0.012702,0.010390,0.014436,0.012729,1.000000

In [50]:
cos_sim[Interested_Movie_ID]

array([[  1.31096471e-02,   1.00000000e+00,   9.44418644e-03, ...,
          1.34289270e-02,   9.61086104e-04,   4.96355875e-03],
       [  2.84413501e-03,   1.30861024e-02,   7.98737751e-03, ...,
          1.48305863e-02,   7.58306966e-03,   1.05293617e-02],
       [  9.75945776e-03,   1.13742963e-02,   9.06565598e-03, ...,
          9.36789954e-03,   2.40102478e-03,   1.14813899e-02],
       [  4.77905113e-03,   1.04962520e-02,   2.80845323e-03, ...,
          1.78730739e-02,   2.41143992e-03,   5.36660507e-03],
       [  2.02944376e-02,   1.54408038e-02,   8.46405079e-03, ...,
          1.26664653e-02,   5.99270202e-04,   6.37538135e-03]])

In [60]:
def Get_Recommendations(cos_sim, id,n,URL):
    '''
    cos_sim is the cosine similarity between each pair of movies
    id is the movie_id
    n is the desired number of recommendations
    '''
    for i in id:
        print("Given that the user liked {}, the following movies are recommended:"
              .format(list(URL["Movie"][URL["Movie_ID"] == i])[0]))
        ind = np.argpartition(cos_sim[i], -n)[-n:]
        print(ind)
        #print(cos_sim[i][ind])
    #y[ind]
Get_Recommendations(cos_sim, Interested_Movie_ID,5,URL)

Given that the user liked  102 Dalmatians, the following movies are recommended:
[3162 2781    1 1438 3002]
Given that the user liked Gladiator, the following movies are recommended:
[2038 2824 1654   73 2283]
Given that the user liked Frozen, the following movies are recommended:
[ 995 2559 1618  610 2772]
Given that the user liked Frozen, the following movies are recommended:
[3512 1604 3232 3554 3316]
Given that the user liked Minions, the following movies are recommended:
[1123 3511 1320 3883  508]

In [25]:
for i in list(URL["Movie"]) if i 

URL[URL["Movie"].isin(["Gladiator","102 Dalmatians"])]

AttributeError: 'Series' object has no attribute 'strip'

# Building the recommender

## Data cleaning

Reading the files data into a data frame

In [121]:
def Read_File(p):
   with open(p, 'r',encoding='utf-8') as f:
    text = f.read()
    #Convert all the text to lower case
    #
    lowers = text.lower()
    #remove the punctuation using the character deletion step of translate
    no_punctuation = lowers.translate(string.punctuation)
    tokens = nltk.word_tokenize(no_punctuation)
    return tokens

def Remove_Stop_Words(tokens):
    filtered = [w for w in tokens if not w in stopwords.words('english')]
    return filtered



def Clean_Text(tokens):
    text = " ".join(tokens)
    #Remove punctuation marks, text in [], (, ), :
    filtered1 = re.sub('\.|\`|\'|\[.*\]|\(|\)|,|:', " ",text)
    
    #Remove any single characters
    filtered1 = re.sub('(^| ).( |$)', " ",filtered1)
    #Remove any contiguous spaces    
    filtered1 = re.sub(' +'," ",filtered1)
    
    #Include only alpha numeric characters
    filtered1=" ".join([i for i in filtered1.split() if re.search('[0-9 a-z]*',i)])
    return filtered1

In [129]:
file_names = os.listdir("./data")
file_names = [i for i in file_names if re.search('[1-9]*\.txt',i)]
y = list()
x = list()
k = 0
for i in file_names:
    y.append(int(i.split(".")[0]))
    #print(y)
    tokens = Read_File("./data/"+i)
    tokens = Remove_Stop_Words(tokens)
    cleaned_text = Clean_Text(tokens)
    x.append(cleaned_text)
    k = k+1
    if(k%100 == 0):
        print("Processed {} files".format(k))

Processed 100 files
Processed 200 files
Processed 300 files
Processed 400 files
Processed 500 files
Processed 600 files
Processed 700 files
Processed 800 files
Processed 900 files
Processed 1000 files
Processed 1100 files
Processed 1200 files
Processed 1300 files
Processed 1400 files
Processed 1500 files
Processed 1600 files
Processed 1700 files
Processed 1800 files
Processed 1900 files
Processed 2000 files
Processed 2100 files
Processed 2200 files
Processed 2300 files
Processed 2400 files
Processed 2500 files
Processed 2600 files
Processed 2700 files
Processed 2800 files
Processed 2900 files
Processed 3000 files
Processed 3100 files
Processed 3200 files
Processed 3300 files
Processed 3400 files
Processed 3500 files
Processed 3600 files
Processed 3700 files
Processed 3800 files
Processed 3900 files
Processed 4000 files

In [142]:
df=pd.DataFrame(list(zip(y,x)),columns = ["Movie_ID","Plot"])
df.to_csv("processed_data.csv",encoding='utf-8',index=False)

In [154]:
df = pd.read_csv("processed_data.csv")
#df.head()
#X = df.pop("Plot")
#display(X.head())
#y = df.pop("Movie_ID")
#display(y)
df.head()

   Movie_ID                                               Plot
0         1  102 dalmatians 2000 american family comedy fil...
1        10  american psycho 2000 american black comedy hor...
2       100  legacy 2000 american documentary film directed...
3      1000  lemony snicket series unfortunate events 2004 ...
4      1001  life death peter sellers 2004 british-american...

In [151]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

In [159]:
start=time.time()
count_vect = CountVectorizer()
X_counts = count_vect.fit_transform(df["Plot"])
#print(X_counts)
tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit_transform(X_counts)
end=time.time()
print("Run time using sklearn package is {} sec\n".format(end-start))
#print "Some of the initial TFIDF rows:\n\n{}".format(X_tfidf[0:2])
print("The TF-IDF matrix has {} rows and {} columns\n".format(X_tfidf.shape[0],X_tfidf.shape[1]))

Run time using sklearn package is 1.7591631412506104 sec

The TF-IDF matrix has 4037 rows and 54075 columns

In [161]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df["Plot"])
print(tfidf_matrix.shape)
#(4, 11)

(4037, 54075)

In [185]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix)
#array([[ 1.        ,  0.36651513,  0.52305744,  0.13448867]])
#sorted(cos_sim[0])[-5:]
ind = np.argpartition(cos_sim[0], -4)[-4:]
cos_sim[0][ind]
y[ind]

1201    2080
2846    3564
3660     659
0          1
Name: Movie_ID, dtype: int64

In [106]:
import nltk
import string

from collections import Counter

def get_tokens():
   with open('./data/34.txt', 'r') as f:
    text = f.read()
    print(text)
    lowers = text.lower()
    #remove the punctuation using the character deletion step of translate
    no_punctuation = lowers.translate(string.punctuation)
    tokens = nltk.word_tokenize(no_punctuation)
    return tokens

tokens = get_tokens()
count = Counter(tokens)
print(count.most_common(10))
print(" ".join(tokens))

Brother is a 2000 American-British-Japanese film starring, written, directed, and edited by Takeshi Kitano.[2]Yamamoto Takeshi Kitano is a brutal and experienced Yakuza enforcer whose boss was killed and whose clan was defeated in a criminal war with a rival family. Surviving clan members have few options: either to join the winners, reconciling with shame and distrust, or to die by committing seppuku. Yamamoto, however, decides to escape to Los Angeles along with his associate Kato (Susumu Terajima). There he finds his estranged half-brother Ken (Claude Maki), who runs a small-time drug business together with his local African-American friends. At the first meeting, Yamamoto badly hurts one of them, Denny (Omar Epps), for an attempt to fraud him. Later, Denny becomes one of the Yamamoto's closest friends and associates.Used to living in a clan and according to its laws, Yamamoto creates a hapless gang out of Ken's buddies. The new gang quickly and brutally attacks Mexican drug bosses and takes control of their territory in LA. They also form an alliance with Shirase (Masaya Kato), a criminal leader of Little Tokyo district, making their group even stronger. As time passes, Yamamoto and his new gang emerge as a formidable force, gradually expanding their turf to such an extent that they confront the powerful Italian Mafia. Now everybody respectfully addresses Yamamoto as Aniki (å…„è²´, elder brother). But soon Aniki suddenly loses any interest in their now successful but dangerous business, spending his time with a girlfriend or just sitting silently thinking about something. However, the Mafia ruthlessly strikes back, and soon Yamamoto and his gang are driven into a disastrous situation of no return as they are hunted down one by one.
[(',', 21), ('.', 13), ('and', 11), ('a', 11), ('yamamoto', 8), ('to', 8), ('with', 6), ('his', 6), ('the', 6), ('of', 6)]
brother is a 2000 american-british-japanese film starring , written , directed , and edited by takeshi kitano . [ 2 ] yamamoto takeshi kitano is a brutal and experienced yakuza enforcer whose boss was killed and whose clan was defeated in a criminal war with a rival family . surviving clan members have few options : either to join the winners , reconciling with shame and distrust , or to die by committing seppuku . yamamoto , however , decides to escape to los angeles along with his associate kato ( susumu terajima ) . there he finds his estranged half-brother ken ( claude maki ) , who runs a small-time drug business together with his local african-american friends . at the first meeting , yamamoto badly hurts one of them , denny ( omar epps ) , for an attempt to fraud him . later , denny becomes one of the yamamoto 's closest friends and associates.used to living in a clan and according to its laws , yamamoto creates a hapless gang out of ken 's buddies . the new gang quickly and brutally attacks mexican drug bosses and takes control of their territory in la . they also form an alliance with shirase ( masaya kato ) , a criminal leader of little tokyo district , making their group even stronger . as time passes , yamamoto and his new gang emerge as a formidable force , gradually expanding their turf to such an extent that they confront the powerful italian mafia . now everybody respectfully addresses yamamoto as aniki ( å…„è²´ , elder brother ) . but soon aniki suddenly loses any interest in their now successful but dangerous business , spending his time with a girlfriend or just sitting silently thinking about something . however , the mafia ruthlessly strikes back , and soon yamamoto and his gang are driven into a disastrous situation of no return as they are hunted down one by one .

In [107]:
from nltk.corpus import stopwords

tokens = get_tokens()
filtered = [w for w in tokens if not w in stopwords.words('english')]
count = Counter(filtered)
print(count.most_common(100))

Brother is a 2000 American-British-Japanese film starring, written, directed, and edited by Takeshi Kitano.[2]Yamamoto Takeshi Kitano is a brutal and experienced Yakuza enforcer whose boss was killed and whose clan was defeated in a criminal war with a rival family. Surviving clan members have few options: either to join the winners, reconciling with shame and distrust, or to die by committing seppuku. Yamamoto, however, decides to escape to Los Angeles along with his associate Kato (Susumu Terajima). There he finds his estranged half-brother Ken (Claude Maki), who runs a small-time drug business together with his local African-American friends. At the first meeting, Yamamoto badly hurts one of them, Denny (Omar Epps), for an attempt to fraud him. Later, Denny becomes one of the Yamamoto's closest friends and associates.Used to living in a clan and according to its laws, Yamamoto creates a hapless gang out of Ken's buddies. The new gang quickly and brutally attacks Mexican drug bosses and takes control of their territory in LA. They also form an alliance with Shirase (Masaya Kato), a criminal leader of Little Tokyo district, making their group even stronger. As time passes, Yamamoto and his new gang emerge as a formidable force, gradually expanding their turf to such an extent that they confront the powerful Italian Mafia. Now everybody respectfully addresses Yamamoto as Aniki (å…„è²´, elder brother). But soon Aniki suddenly loses any interest in their now successful but dangerous business, spending his time with a girlfriend or just sitting silently thinking about something. However, the Mafia ruthlessly strikes back, and soon Yamamoto and his gang are driven into a disastrous situation of no return as they are hunted down one by one.
[(',', 21), ('.', 13), ('yamamoto', 8), ('(', 5), (')', 5), ('one', 4), ('gang', 4), ('clan', 3), ('ken', 2), ('takeshi', 2), ('however', 2), ('new', 2), ('mafia', 2), ('kato', 2), ('kitano', 2), ('drug', 2), ('brother', 2), ('whose', 2), ('criminal', 2), ('soon', 2), ("'s", 2), ('time', 2), ('aniki', 2), ('business', 2), ('denny', 2), ('friends', 2), ('decides', 1), ('alliance', 1), ('even', 1), ('distrust', 1), ('suddenly', 1), ('group', 1), ('return', 1), ('first', 1), ('2000', 1), ('interest', 1), ('driven', 1), ('later', 1), ('making', 1), ('estranged', 1), ('written', 1), ('turf', 1), ('everybody', 1), ('hapless', 1), ('options', 1), ('successful', 1), ('american-british-japanese', 1), ('directed', 1), ('gradually', 1), ('enforcer', 1), ('masaya', 1), ('force', 1), ('members', 1), ('epps', 1), ('quickly', 1), ('join', 1), ('committing', 1), ('closest', 1), ('addresses', 1), ('half-brother', 1), ('edited', 1), ('badly', 1), ('defeated', 1), ('living', 1), ('takes', 1), ('form', 1), ('elder', 1), ('situation', 1), ('also', 1), ('brutal', 1), ('surviving', 1), ('claude', 1), ('film', 1), ('together', 1), ('loses', 1), ('passes', 1), ('creates', 1), ('control', 1), ('die', 1), ('italian', 1), ('hunted', 1), ('according', 1), ('ruthlessly', 1), ('[', 1), ('omar', 1), ('small-time', 1), ('angeles', 1), ('bosses', 1), ('local', 1), ('respectfully', 1), ('attacks', 1), ('å…„è²´', 1), ('war', 1), ('silently', 1), (']', 1), ('hurts', 1), ('either', 1), ('2', 1), ('thinking', 1), (':', 1)]

In [108]:
filtered

['brother',
 '2000',
 'american-british-japanese',
 'film',
 'starring',
 ',',
 'written',
 ',',
 'directed',
 ',',
 'edited',
 'takeshi',
 'kitano',
 '.',
 '[',
 '2',
 ']',
 'yamamoto',
 'takeshi',
 'kitano',
 'brutal',
 'experienced',
 'yakuza',
 'enforcer',
 'whose',
 'boss',
 'killed',
 'whose',
 'clan',
 'defeated',
 'criminal',
 'war',
 'rival',
 'family',
 '.',
 'surviving',
 'clan',
 'members',
 'options',
 ':',
 'either',
 'join',
 'winners',
 ',',
 'reconciling',
 'shame',
 'distrust',
 ',',
 'die',
 'committing',
 'seppuku',
 '.',
 'yamamoto',
 ',',
 'however',
 ',',
 'decides',
 'escape',
 'los',
 'angeles',
 'along',
 'associate',
 'kato',
 '(',
 'susumu',
 'terajima',
 ')',
 '.',
 'finds',
 'estranged',
 'half-brother',
 'ken',
 '(',
 'claude',
 'maki',
 ')',
 ',',
 'runs',
 'small-time',
 'drug',
 'business',
 'together',
 'local',
 'african-american',
 'friends',
 '.',
 'first',
 'meeting',
 ',',
 'yamamoto',
 'badly',
 'hurts',
 'one',
 ',',
 'denny',
 '(',
 'omar',
 'epps',
 ')',
 ',',
 'attempt',
 'fraud',
 '.',
 'later',
 ',',
 'denny',
 'becomes',
 'one',
 'yamamoto',
 "'s",
 'closest',
 'friends',
 'associates.used',
 'living',
 'clan',
 'according',
 'laws',
 ',',
 'yamamoto',
 'creates',
 'hapless',
 'gang',
 'ken',
 "'s",
 'buddies',
 '.',
 'new',
 'gang',
 'quickly',
 'brutally',
 'attacks',
 'mexican',
 'drug',
 'bosses',
 'takes',
 'control',
 'territory',
 'la',
 '.',
 'also',
 'form',
 'alliance',
 'shirase',
 '(',
 'masaya',
 'kato',
 ')',
 ',',
 'criminal',
 'leader',
 'little',
 'tokyo',
 'district',
 ',',
 'making',
 'group',
 'even',
 'stronger',
 '.',
 'time',
 'passes',
 ',',
 'yamamoto',
 'new',
 'gang',
 'emerge',
 'formidable',
 'force',
 ',',
 'gradually',
 'expanding',
 'turf',
 'extent',
 'confront',
 'powerful',
 'italian',
 'mafia',
 '.',
 'everybody',
 'respectfully',
 'addresses',
 'yamamoto',
 'aniki',
 '(',
 'å…„è²´',
 ',',
 'elder',
 'brother',
 ')',
 '.',
 'soon',
 'aniki',
 'suddenly',
 'loses',
 'interest',
 'successful',
 'dangerous',
 'business',
 ',',
 'spending',
 'time',
 'girlfriend',
 'sitting',
 'silently',
 'thinking',
 'something',
 '.',
 'however',
 ',',
 'mafia',
 'ruthlessly',
 'strikes',
 'back',
 ',',
 'soon',
 'yamamoto',
 'gang',
 'driven',
 'disastrous',
 'situation',
 'return',
 'hunted',
 'one',
 'one',
 '.']

In [109]:
import re
#filtered1 = ['[37]']
#[i for i in filtered1 if re.search('.*\[.*\].*', i)]
["" for i in filtered if re.search(' *\'s.*', i)]

['', '']

In [110]:
filtered=" ".join(filtered)
filtered

"brother 2000 american-british-japanese film starring , written , directed , edited takeshi kitano . [ 2 ] yamamoto takeshi kitano brutal experienced yakuza enforcer whose boss killed whose clan defeated criminal war rival family . surviving clan members options : either join winners , reconciling shame distrust , die committing seppuku . yamamoto , however , decides escape los angeles along associate kato ( susumu terajima ) . finds estranged half-brother ken ( claude maki ) , runs small-time drug business together local african-american friends . first meeting , yamamoto badly hurts one , denny ( omar epps ) , attempt fraud . later , denny becomes one yamamoto 's closest friends associates.used living clan according laws , yamamoto creates hapless gang ken 's buddies . new gang quickly brutally attacks mexican drug bosses takes control territory la . also form alliance shirase ( masaya kato ) , criminal leader little tokyo district , making group even stronger . time passes , yamamoto new gang emerge formidable force , gradually expanding turf extent confront powerful italian mafia . everybody respectfully addresses yamamoto aniki ( å…„è²´ , elder brother ) . soon aniki suddenly loses interest successful dangerous business , spending time girlfriend sitting silently thinking something . however , mafia ruthlessly strikes back , soon yamamoto gang driven disastrous situation return hunted one one ."

In [111]:
filtered1 = re.sub('\.|\`|\'|\[.*\]|\(|\)|,|:', " ",filtered)
#print(filtered1)
filtered1 = re.sub('(^| ).( |$)', " ",filtered1)
filtered1 = re.sub(' +'," ",filtered1)


filtered1=" ".join([i for i in filtered1.split() if re.search('[0-9 a-z]*',i)])
print(filtered1)

brother 2000 american-british-japanese film starring written directed edited takeshi kitano yamamoto takeshi kitano brutal experienced yakuza enforcer whose boss killed whose clan defeated criminal war rival family surviving clan members options either join winners reconciling shame distrust die committing seppuku yamamoto however decides escape los angeles along associate kato susumu terajima finds estranged half-brother ken claude maki runs small-time drug business together local african-american friends first meeting yamamoto badly hurts one denny omar epps attempt fraud later denny becomes one yamamoto closest friends associates used living clan according laws yamamoto creates hapless gang ken buddies new gang quickly brutally attacks mexican drug bosses takes control territory la also form alliance shirase masaya kato criminal leader little tokyo district making group even stronger time passes yamamoto new gang emerge formidable force gradually expanding turf extent confront powerful italian mafia everybody respectfully addresses yamamoto aniki å…„è²´ elder brother soon aniki suddenly loses interest successful dangerous business spending time girlfriend sitting silently thinking something however mafia ruthlessly strikes back soon yamamoto gang driven disastrous situation return hunted one one

In [89]:
count = Counter(filtered1.split())
print(filtered1)
print(count.most_common(100))

102 dalmatians 2000 american family comedy film directed kevin lima live-action directorial debut produced edward  feldman walt disney pictures sequel 1996 film 101 dalmatians stars glenn close reprising role cruella de vil attempts steal puppies  grandest  fur coat yet close tim mcinnerny two actors first film return sequel however film nominated academy award best costume design lost gladiator   three years prison cruella de vil cured desire fur coats dr  pavlov released custody probation office provision forced pay remainder fortune eight million pounds dog shelters borough westminster repeat crime cruella therefore mends working relationship valet alonzo lock away fur coats cruella  probation officer chloe simon nevertheless suspects partly chloe owner now-adult dipstick one original 15 puppies previous film   dipstick  mate dottie recently given birth three puppies domino little dipper oddball lacks spots   mend reputation cruella buys second chance dog shelter owned kevin shepherd resolve financial insolvency verge eviction meanwhile dr  pavlov discovers therapy  subjects subjected loud noises revert original states conceals discovery big ben rings presence cruella reverts former personality enlists help french furrier jean-pierre lepelt steal 102 dalmatian puppies new fur coat kevin tells chloe cruella violates parole entire fortune go since dog shelter one borough westminster cruella kevin framed theft puppies invites chloe dinner lepelt steals dottie three puppies dipstick hurries back apartment hides lepelt  truck later captured train station chloe rushes home save pets arrives late joined kevin escaped prison help dogs talking parrot waddlesworth upon finding ticket orient express paris dropped lepelt kevin chloe attempt fail stop cruella lepelt oddball waddlesworth pursue enemies secretly paris kevin chloe save captive puppies seen locked cellar puppies flee cruella goes puppies alone alonzo scolded beyond patience enough abused defeats lepelt frees kevin chloe give chase wedding cake factory puppies kevin  dogs imprison cruella immense cake lepelt thereupon arrested kevin chloe personally awarded remnants cruella  fortune alonzo oddball  coat develops spots
[('cruella', 12), ('puppies', 10), ('kevin', 10), ('chloe', 9), ('lepelt', 7), ('film', 5), ('fur', 4), ('alonzo', 3), ('fortune', 3), ('three', 3), ('dog', 3), ('dipstick', 3), ('coat', 3), ('oddball', 3), ('one', 2), ('save', 2), ('close', 2), ('sequel', 2), ('dr', 2), ('steal', 2), ('dottie', 2), ('vil', 2), ('westminster', 2), ('original', 2), ('coats', 2), ('de', 2), ('dalmatians', 2), ('waddlesworth', 2), ('probation', 2), ('dogs', 2), ('paris', 2), ('spots', 2), ('102', 2), ('borough', 2), ('cake', 2), ('shelter', 2), ('pavlov', 2), ('prison', 2), ('help', 2), ('since', 1), ('pets', 1), ('best', 1), ('pay', 1), ('award', 1), ('return', 1), ('101', 1), ('grandest', 1), ('attempt', 1), ('joined', 1), ('violates', 1), ('pursue', 1), ('reverts', 1), ('1996', 1), ('remainder', 1), ('mcinnerny', 1), ('directed', 1), ('design', 1), ('repeat', 1), ('apartment', 1), ('invites', 1), ('recently', 1), ('however', 1), ('lock', 1), ('abused', 1), ('eight', 1), ('therapy', 1), ('tim', 1), ('role', 1), ('personally', 1), ('working', 1), ('stop', 1), ('comedy', 1), ('therefore', 1), ('partly', 1), ('released', 1), ('disney', 1), ('attempts', 1), ('escaped', 1), ('framed', 1), ('home', 1), ('captured', 1), ('go', 1), ('back', 1), ('reprising', 1), ('enough', 1), ('dipper', 1), ('hides', 1), ('finding', 1), ('theft', 1), ('forced', 1), ('office', 1), ('defeats', 1), ('cured', 1), ('little', 1), ('debut', 1), ('now-adult', 1), ('later', 1), ('thereupon', 1), ('discovers', 1), ('eviction', 1)]